inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

# Too much time is wasted arguing about this. It really doesn't matter which
# string delimiter you prefer.
Style/StringLiterals:
  Enabled: false
