databases:
  - name: data_software_catalogue
    databaseName: data_software_catalogue
    user: data_software_catalogue

services:
  - type: web
    name: data_software_catalogue
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: data_software_catalogue
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
