require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/software_instances", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SoftwareInstance. As you add validations to SoftwareInstance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SoftwareInstance.create! valid_attributes
      get software_instances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      software_instance = SoftwareInstance.create! valid_attributes
      get software_instance_url(software_instance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_software_instance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      software_instance = SoftwareInstance.create! valid_attributes
      get edit_software_instance_url(software_instance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SoftwareInstance" do
        expect {
          post software_instances_url, params: { software_instance: valid_attributes }
        }.to change(SoftwareInstance, :count).by(1)
      end

      it "redirects to the created software_instance" do
        post software_instances_url, params: { software_instance: valid_attributes }
        expect(response).to redirect_to(software_instance_url(SoftwareInstance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SoftwareInstance" do
        expect {
          post software_instances_url, params: { software_instance: invalid_attributes }
        }.to change(SoftwareInstance, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post software_instances_url, params: { software_instance: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested software_instance" do
        software_instance = SoftwareInstance.create! valid_attributes
        patch software_instance_url(software_instance), params: { software_instance: new_attributes }
        software_instance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the software_instance" do
        software_instance = SoftwareInstance.create! valid_attributes
        patch software_instance_url(software_instance), params: { software_instance: new_attributes }
        software_instance.reload
        expect(response).to redirect_to(software_instance_url(software_instance))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        software_instance = SoftwareInstance.create! valid_attributes
        patch software_instance_url(software_instance), params: { software_instance: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested software_instance" do
      software_instance = SoftwareInstance.create! valid_attributes
      expect {
        delete software_instance_url(software_instance)
      }.to change(SoftwareInstance, :count).by(-1)
    end

    it "redirects to the software_instances list" do
      software_instance = SoftwareInstance.create! valid_attributes
      delete software_instance_url(software_instance)
      expect(response).to redirect_to(software_instances_url)
    end
  end
end
